export const GET_DATA_REQUEST = "GET_DATA_REQUEST";
export const GET_DATA_SUCCESS = "GET_DATA_SUCCESS";
export const GET_DATA_ERROR = "GET_DATA_ERROR";
export const GET_DATA_RESET = "GET_DATA_RESET";

export const GET_PRODUCT_REQUEST = "GET_PRODUCT_REQUEST";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_ERROR = "GET_PRODUCT_ERROR";

export const NEW_PRODUCT_REQUEST = "NEW_PRODUCT_REQUEST";
export const NEW_PRODUCT_SUCCESS = "NEW_PRODUCT_SUCCESS";
export const NEW_PRODUCT_ERROR = "NEW_PRODUCT_ERROR";

export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_ERROR = "DELETE_PRODUCT_ERROR";

export const EDIT_PRODUCT_REQUEST = "EDIT_PRODUCT_REQUEST";
export const EDIT_PRODUCT_SUCCESS = "EDIT_PRODUCT_SUCCESS";
export const EDIT_PRODUCT_ERROR = "EDIT_PRODUCT_ERROR";

export const GET_DISTRICT_REQUEST = "GET_DISTRICT_REQUEST";
export const GET_DISTRICT_SUCCESS = "GET_DISTRICT_SUCCESS";
export const GET_DISTRICT_ERROR = "GET_DISTRICT_ERROR";

export const GET_VILLAGE_REQUEST = "GET_VILLAGE_REQUEST";
export const GET_VILLAGE_SUCCESS = "GET_VILLAGE_SUCCESS";
export const GET_VILLAGE_ERROR = "GET_VILLAGE_ERROR";

export const NEW_CUSTOMER_REQUEST = "NEW_CUSTOMER_REQUEST";
export const NEW_CUSTOMER_SUCCESS = "NEW_CUSTOMER_SUCCESS";
export const NEW_CUSTOMER_ERROR = "NEW_CUSTOMER_ERROR";

export const GET_CUSTOMER_REQUEST = "GET_CUSTOMER_REQUEST";
export const GET_CUSTOMER_SUCCESS = "GET_CUSTOMER_SUCCESS";
export const GET_CUSTOMER_ERROR = "GET_CUSTOMER_ERROR";

export const PRODUCT_RESET = "PRODUCT_RESET";
export const ZONE_RESET = "ZONE_RESET";
export const CUSTOMER_RESET = "CUSTOMER_RESET";
